'use strict';
const LV={1:{c:'#ffffcd',t:'Sehr geringe Gefahr',r:[255,255,205]},2:{c:'#ffd879',t:'Geringe Gefahr',r:[255,216,121]},3:{c:'#ff8c39',t:'Mittlere Gefahr',r:[255,140,57]},4:{c:'#e9161d',t:'Hohe Gefahr',r:[233,22,29]},5:{c:'#7f0126',t:'Sehr hohe Gefahr',r:[127,1,38]}};
const PALETTES={
  mima:{name:'MiMa-Farben',logo:'https://cdn.jsdelivr.net/gh/mad-desigen/Waldbranntkarte@main/MiMa-Logo.svg',logoAlt:'MiMa',script:'https://raw.githubusercontent.com/mad-desigen/Waldbranntkarte/main/WBI_GEOlayers_Einfaerben_MiMa-Farben.jsx',colors:{1:'#d0cbc2',2:'#f8f287',3:'#fabb7a',4:'#fd6165',5:'#a62121'}},
  aktuell:{name:'Aktuell-Farben',logo:'https://cdn.jsdelivr.net/gh/mad-desigen/Waldbranntkarte@main/AKTUELL-Logo.svg',logoAlt:'Aktuell',script:'https://raw.githubusercontent.com/mad-desigen/Waldbranntkarte/main/WBI_GEOlayers_Einfaerben_Aktuell-Farben.jsx',colors:{1:'#c1bdb2',2:'#fec804',3:'#ff8b00',4:'#c61e1e',5:'#71207f'}}
};
const $=id=>document.getElementById(id),S={states:null,mask:null,bounds:null,stateLayer:null,raster:null,vector:null,fitted:null,geo:null,status:null,dataStale:false,day:0,palette:'mima',version:Date.now()};
const map=L.map('map',{preferCanvas:true,minZoom:5,maxZoom:12,maxBounds:[[45.5,3.5],[56.6,17.5]],maxBoundsViscosity:.8});map.attributionControl.setPrefix(false);map.attributionControl.addAttribution('<a href="https://www.wettergefahren.de/warnungen/indizes/waldbrand.html" target="_blank">WBI © DWD</a>');
for(let i=0;i<5;i++){const d=new Date();d.setDate(d.getDate()+i);$('day').add(new Option(`${i?`+${i} Tag${i>1?'e':''}`:'Heute'} · ${new Intl.DateTimeFormat('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'}).format(d)}`,i))}
function palette(){return PALETTES[S.palette]}
function renderLegend(){const box=$('legend');if(!box)return;const p=palette();box.innerHTML='';for(let n=1;n<=5;n++)box.insertAdjacentHTML('beforeend',`<div><span class="sw" style="background:${p.colors[n]}"></span>${n} · ${LV[n].t}</div>`)}
function applyPalette(){const paletteSelect=$('palette');S.palette=paletteSelect?paletteSelect.value:'mima';const p=palette(),logo=$('brandLogo'),script=$('scriptDownload');if(logo){logo.src=asset(p.logo,true);logo.alt=p.logoAlt}if(script){script.href=p.script;script.download=p.script;script.textContent=p.name+' herunterladen'}renderLegend();if(S.geo){for(const f of S.geo.features||[]){const n=Number(f?.properties?.wbi_stufe);if(p.colors[n]){f.properties.farbe=p.colors[n];f.properties.gestaltungsfarbe=p.colors[n];f.properties.ae_farbe=p.colors[n]}}S.geo.metadata.farbschema=p.name;renderVector()}}
function setText(id,text){const el=$(id);if(el)el.textContent=text}function busy(on,text=''){const loading=$('loading');if(loading)loading.hidden=!on;if(text)setText('loadingText',text)}function note(text,type=''){const el=$('notice');if(!el)return;el.className='notice '+type;el.textContent=text}function status(text){setText('topState',text)}function asset(path,force=false){return`${path}?v=${encodeURIComponent(force?Date.now():S.version)}`}function my(lat){lat=Math.max(-85.0511,Math.min(85.0511,lat))*Math.PI/180;return Math.log(Math.tan(Math.PI/4+lat/2))}function imy(v){return(2*Math.atan(Math.exp(v))-Math.PI/2)*180/Math.PI}
function maskFeature(fc){const coordinates=[];for(const f of fc.features||[]){const g=f&&f.geometry;if(!g)continue;if(g.type==='Polygon')coordinates.push(g.coordinates);else if(g.type==='MultiPolygon')coordinates.push(...g.coordinates)}if(!coordinates.length)throw Error('Die Deutschland-Geometrie enthält keine Polygone.');return turf.feature({type:'MultiPolygon',coordinates},{__mask:1})}
function drawGeom(ctx,g,w,h,b){const[west,south,east,north]=b,ny=my(north),sy=my(south),pt=([lon,lat])=>[(lon-west)/(east-west)*w,(my(lat)-ny)/(sy-ny)*h],ring=r=>{r.forEach((q,i)=>{const[x,y]=pt(q);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath()};ctx.beginPath();if(g.type==='Polygon')g.coordinates.forEach(ring);else g.coordinates.forEach(p=>p.forEach(ring))}
function nearest(r,g,b){let level=0,dist=1e9;for(const[n,v]of Object.entries(LV)){const d=(r-v.r[0])**2+(g-v.r[1])**2+(b-v.r[2])**2;if(d<dist){dist=d;level=+n}}return{level,dist}}
function isBorderPixel(r,g,b){const mx=Math.max(r,g,b),mn=Math.min(r,g,b),sat=mx-mn,light=(mx+mn)/2;return sat<=18&&light>35&&light<235}
function sourceCanvas(img){const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0);const raw=x.getImageData(0,0,c.width,c.height),p=raw.data;let l=c.width,t=c.height,r=-1,b=-1;const labels=new Uint8Array(c.width*c.height),scanH=Math.floor(c.height*.9);for(let y=0;y<scanH;y++)for(let z=0;z<c.width;z++){const i=(y*c.width+z)*4,R=p[i],G=p[i+1],B=p[i+2];let n=0;if(isBorderPixel(R,G,B)){n=6}else{const m=nearest(R,G,B);if(m.dist<1600)n=m.level}if(n){labels[y*c.width+z]=n;l=Math.min(l,z);r=Math.max(r,z);t=Math.min(t,y);b=Math.max(b,y)}}if(r<l)throw Error('In der DWD-Grafik wurden keine WBI-Farben erkannt.');const w=r-l+1,h=b-t+1,crop=new Uint8Array(w*h);for(let y=0;y<h;y++)for(let z=0;z<w;z++)crop[y*w+z]=labels[(y+t)*c.width+z+l];return{labels:crop,box:{l:0,t:0,r:w-1,b:h-1,w,h}}}
