'use strict';
const LV={1:{c:'#ffffcd',t:'Sehr geringe Gefahr',r:[255,255,205]},2:{c:'#ffd879',t:'Geringe Gefahr',r:[255,216,121]},3:{c:'#ff8c39',t:'Mittlere Gefahr',r:[255,140,57]},4:{c:'#e9161d',t:'Hohe Gefahr',r:[233,22,29]},5:{c:'#7f0126',t:'Sehr hohe Gefahr',r:[127,1,38]}};
const PALETTES={
  mima:{name:'MiMa-Farben',logo:'MiMa-Logo.svg',logoAlt:'MiMa',script:'WBI_GEOlayers_Einfaerben_MiMa-Farben.jsx',colors:{1:'#d0cbc2',2:'#f8f287',3:'#fabb7a',4:'#fd6165',5:'#a62121'}},
  aktuell:{name:'Aktuell-Farben',logo:'AKTUELL-Logo.svg',logoAlt:'Aktuell',script:'WBI_GEOlayers_Einfaerben_Aktuell-Farben.jsx',colors:{1:'#c1bdb2',2:'#fec804',3:'#ff8b00',4:'#c61e1e',5:'#71207f'}}
};
const $=id=>document.getElementById(id),S={states:null,mask:null,bounds:null,stateLayer:null,raster:null,vector:null,fitted:null,geo:null,day:0,palette:'mima',version:Date.now()};
const map=L.map('map',{preferCanvas:true,minZoom:5,maxZoom:12,maxBounds:[[45.5,3.5],[56.6,17.5]],maxBoundsViscosity:.8});map.attributionControl.setPrefix(false);map.attributionControl.addAttribution('<a href="https://www.wettergefahren.de/warnungen/indizes/waldbrand.html" target="_blank">WBI © DWD</a>');
for(let i=0;i<5;i++){const d=new Date();d.setDate(d.getDate()+i);$('day').add(new Option(`${i?`+${i} Tag${i>1?'e':''}`:'Heute'} · ${new Intl.DateTimeFormat('de-DE',{weekday:'short',day:'2-digit',month:'2-digit',year:'numeric'}).format(d)}`,i))}
function palette(){return PALETTES[S.palette]}
function renderLegend(){const box=$('legend');if(!box)return;const p=palette();box.innerHTML='';for(let n=1;n<=5;n++)box.insertAdjacentHTML('beforeend',`<div><span class="sw" style="background:${p.colors[n]}"></span>${n} · ${LV[n].t}</div>`)}
function applyPalette(){const paletteSelect=$('palette');S.palette=paletteSelect?paletteSelect.value:'mima';const p=palette(),logo=$('brandLogo'),script=$('scriptDownload');if(logo){logo.src=asset(p.logo,true);logo.alt=p.logoAlt}if(script){script.href=p.script;script.download=p.script;script.textContent=p.name+' herunterladen'}renderLegend();if(S.geo){for(const f of S.geo.features||[]){const n=Number(f?.properties?.wbi_stufe);if(p.colors[n])f.properties.farbe=p.colors[n]}S.geo.metadata.farbschema=p.name;renderVector()}}
function setText(id,text){const el=$(id);if(el)el.textContent=text}function busy(on,text=''){const loading=$('loading');if(loading)loading.hidden=!on;if(text)setText('loadingText',text)}function note(text,type=''){const el=$('notice');if(!el)return;el.className='notice '+type;el.textContent=text}function status(text){setText('topState',text)}function asset(path,force=false){return`${path}?v=${encodeURIComponent(force?Date.now():S.version)}`}function my(lat){lat=Math.max(-85.0511,Math.min(85.0511,lat))*Math.PI/180;return Math.log(Math.tan(Math.PI/4+lat/2))}function imy(v){return(2*Math.atan(Math.exp(v))-Math.PI/2)*180/Math.PI}
function maskFeature(fc){const coordinates=[];for(const f of fc.features||[]){const g=f&&f.geometry;if(!g)continue;if(g.type==='Polygon')coordinates.push(g.coordinates);else if(g.type==='MultiPolygon')coordinates.push(...g.coordinates)}if(!coordinates.length)throw Error('Die Deutschland-Geometrie enthält keine Polygone.');return turf.feature({type:'MultiPolygon',coordinates},{__mask:1})}
function drawGeom(ctx,g,w,h,b){const[west,south,east,north]=b,ny=my(north),sy=my(south),pt=([lon,lat])=>[(lon-west)/(east-west)*w,(my(lat)-ny)/(sy-ny)*h],ring=r=>{r.forEach((q,i)=>{const[x,y]=pt(q);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath()};ctx.beginPath();if(g.type==='Polygon')g.coordinates.forEach(ring);else g.coordinates.forEach(p=>p.forEach(ring))}
function nearest(r,g,b){let level=0,dist=1e9;for(const[n,v]of Object.entries(LV)){const d=(r-v.r[0])**2+(g-v.r[1])**2+(b-v.r[2])**2;if(d<dist){dist=d;level=+n}}return{level,dist}}
function isBorderPixel(r,g,b){const mx=Math.max(r,g,b),mn=Math.min(r,g,b),sat=mx-mn,light=(mx+mn)/2;return sat<=18&&light>35&&light<235}
function sourceCanvas(img){const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;const x=c.getContext('2d',{willReadFrequently:true});x.drawImage(img,0,0);const raw=x.getImageData(0,0,c.width,c.height),p=raw.data;let l=c.width,t=c.height,r=-1,b=-1;const labels=new Uint8Array(c.width*c.height),scanH=Math.floor(c.height*.9);for(let y=0;y<scanH;y++)for(let z=0;z<c.width;z++){const i=(y*c.width+z)*4,R=p[i],G=p[i+1],B=p[i+2];let n=0;if(isBorderPixel(R,G,B)){n=6}else{const m=nearest(R,G,B);if(m.dist<1600)n=m.level}if(n){labels[y*c.width+z]=n;l=Math.min(l,z);r=Math.max(r,z);t=Math.min(t,y);b=Math.max(b,y)}}if(r<l)throw Error('In der DWD-Grafik wurden keine WBI-Farben erkannt.');const w=r-l+1,h=b-t+1,crop=new Uint8Array(w*h);for(let y=0;y<h;y++)for(let z=0;z<w;z++)crop[y*w+z]=labels[(y+t)*c.width+z+l];return{labels:crop,box:{l:0,t:0,r:w-1,b:h-1,w,h}}}
function fillGaps(labels,inMask,w,h){let cur=labels.slice();for(let round=0;round<14;round++){const next=cur.slice();let changed=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=y*w+x;if(!inMask[i])continue;const v=cur[i];if(v>=1&&v<=5)continue;const counts=[0,0,0,0,0,0];let total=0;for(let dy=-2;dy<=2;dy++){const yy=y+dy;if(yy<0||yy>=h)continue;for(let dx=-2;dx<=2;dx++){if(!dx&&!dy)continue;const xx=x+dx;if(xx<0||xx>=w)continue;const q=cur[yy*w+xx];if(q>=1&&q<=5){counts[q]++;total++}}}if(total<3)continue;let best=1;for(let n=2;n<=4;n++)if(counts[n]>counts[best])best=n;if(counts[5]>=Math.max(4,Math.ceil(total*.6))&&counts[5]>counts[best])best=5;next[i]=best;changed++}cur=next;if(!changed)break}return cur}
function alphaBox(im){let l=im.width,t=im.height,r=-1,b=-1;for(let y=0;y<im.height;y++)for(let x=0;x<im.width;x++)if(im.data[(y*im.width+x)*4+3]){l=Math.min(l,x);r=Math.max(r,x);t=Math.min(t,y);b=Math.max(b,y)}return r<l?null:{l,t,r,b,w:r-l+1,h:b-t+1}}
function drawStatesMask(ctx,fc,w,h,bbox){ctx.fillStyle='#fff';for(const f of fc.features||[]){const g=f&&f.geometry;if(!g||!/Polygon/.test(g.type))continue;drawGeom(ctx,g,w,h,bbox);ctx.fill('evenodd')}}
function sourceAt(labels,w,h,x,y){const X=Math.round(x),Y=Math.round(y);return X>=0&&Y>=0&&X<w&&Y<h&&labels[Y*w+X]>0}
function score(p,src,tgt,sb,tb){const[kx,ky,dx,dy,sh]=p,scx=(sb.l+sb.r)/2,scy=(sb.t+sb.b)/2,tcx=(tb.l+tb.r)/2,tcy=(tb.t+tb.b)/2,step=Math.max(4,Math.round(Math.max(tb.w,tb.h)/210));let a=0,b=0,c=0;for(let y=tb.t;y<=tb.b;y+=step)for(let x=tb.l;x<=tb.r;x+=step){const T=tgt.data[(y*tgt.width+x)*4+3]>0,X=sourceAt(src.labels,sb.w,sb.h,scx+(x-tcx)*kx+dx+sh*(y-tcy),scy+(y-tcy)*ky+dy);if(T)a++;if(X)b++;if(T&&X)c++}return 2*c/Math.max(1,a+b)}
function optimize(src,tgt,sb,tb){let p=[sb.w/tb.w,sb.h/tb.h,0,0,0],st=[p[0]*.04,p[1]*.04,Math.max(3,sb.w*.009),Math.max(3,sb.h*.007),.01],best=score(p,src,tgt,sb,tb);for(let round=0;round<7;round++){let changed=true,g=0;while(changed&&g++<12){changed=false;for(let i=0;i<p.length;i++)for(const s of[-1,1]){const q=p.slice();q[i]+=s*st[i];if(q[0]<=0||q[1]<=0)continue;const n=score(q,src,tgt,sb,tb);if(n>best){p=q;best=n;changed=true}}}st=st.map(v=>v*.55)}return p}
function fit(img){const src=sourceCanvas(img),bbox=turf.bbox(S.states),[west,south,east,north]=bbox,ny=my(north),sy=my(south),h=1100,w=Math.max(320,Math.round(h*((east-west)*Math.PI/180)/(ny-sy))),mc=document.createElement('canvas');mc.width=w;mc.height=h;const mx=mc.getContext('2d',{willReadFrequently:true});drawStatesMask(mx,S.states,w,h,bbox);const mask=mx.getImageData(0,0,w,h),sb=src.box,tb=alphaBox(mask);if(!tb)throw Error('Die amtliche Deutschlandmaske konnte nicht gezeichnet werden.');const p=optimize(src,mask,sb,tb),[kx,ky,dx,dy,sh]=p,scx=(sb.l+sb.r)/2,scy=(sb.t+sb.b)/2,tcx=(tb.l+tb.r)/2,tcy=(tb.t+tb.b)/2,warped=new Uint8Array(w*h),inMask=new Uint8Array(w*h);for(let y=tb.t;y<=tb.b;y++)for(let x=tb.l;x<=tb.r;x++){const i=y*w+x;if(!mask.data[i*4+3])continue;inMask[i]=1;const sx=Math.round(scx+(x-tcx)*kx+dx+sh*(y-tcy)),sy2=Math.round(scy+(y-tcy)*ky+dy);warped[i]=(sx>=0&&sy2>=0&&sx<sb.w&&sy2<sb.h)?src.labels[sy2*sb.w+sx]:0}const filled=fillGaps(warped,inMask,w,h),out=document.createElement('canvas');out.width=w;out.height=h;const ox=out.getContext('2d',{willReadFrequently:true}),oi=ox.createImageData(w,h);for(let i=0;i<filled.length;i++){const n=filled[i];if(n<1||n>5)continue;const q=LV[n].r,j=i*4;oi.data[j]=q[0];oi.data[j+1]=q[1];oi.data[j+2]=q[2];oi.data[j+3]=255}ox.putImageData(oi,0,0);return{canvas:out,labels:filled,w,h,bbox}}
function renderStates(){if(S.stateLayer)map.removeLayer(S.stateLayer);S.stateLayer=L.geoJSON(S.states,{style:{color:'#5f6d64',weight:1,opacity:.75,fillOpacity:0},interactive:false}).addTo(map)}
function renderVector(){if(S.vector)map.removeLayer(S.vector);if(!S.geo)return;S.vector=L.geoJSON(S.geo,{style:f=>({color:f.properties.farbe,weight:0,opacity:0,fillColor:f.properties.farbe,fillOpacity:.64})}).addTo(map);if(S.stateLayer){S.stateLayer.addTo(map);S.stateLayer.bringToFront()}}
async function loadStatus(){try{const r=await fetch(asset('data/status.json',true),{cache:'no-store'}),j=await r.json();S.version=j.updated_at||Date.now();const d=new Date(j.updated_at);setText('stamp',Number.isNaN(d.getTime())?'automatisch aktualisiert':new Intl.DateTimeFormat('de-DE',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Berlin'}).format(d)+' Uhr')}catch{setText('stamp','Datenstand unbekannt')}}
async function init(){busy(true);try{applyPalette();await loadStatus();const r=await fetch(asset('data/states.geojson'),{cache:'no-store'});if(!r.ok)throw Error('Deutschland-Geometrie fehlt (HTTP '+r.status+').');S.states=await r.json();S.mask=maskFeature(S.states);const b=turf.bbox(S.mask);S.bounds=L.latLngBounds([b[1],b[0]],[b[3],b[2]]);renderStates();map.fitBounds(S.bounds,{padding:[20,20]});await loadDay();status('Bereit')}catch(e){status('Fehler');note(e.message,'err')}finally{busy(false);map.invalidateSize()}}
async function loadDay(force=false){busy(true,'DWD-Flächenkarte wird bereinigt und passgenau angepasst …');try{S.day=+$('day').value;const r=await fetch(asset(`data/wbi_${S.day}.png`,force),{cache:'no-store'});if(!r.ok)throw Error('DWD-Grafik fehlt (HTTP '+r.status+').');const blob=await r.blob(),img=await new Promise((ok,no)=>{const u=URL.createObjectURL(blob),i=new Image();i.onload=()=>{URL.revokeObjectURL(u);ok(i)};i.onerror=no;i.src=u}),f=fit(img);S.fitted=f;if(S.raster)map.removeLayer(S.raster);S.raster=L.imageOverlay(f.canvas.toDataURL('image/png'),S.bounds,{opacity:.86,interactive:false}).addTo(map);S.geo=null;$('download').disabled=true;await generate()}finally{busy(false)}}
function point(x,y,c,r){const b=S.fitted.bbox,[west,south,east,north]=b,ny=my(north),sy=my(south);return[west+(east-west)*x/c,imy(ny+(sy-ny)*y/r)]}function sampleFit(xf,yf){const w=S.fitted.w,h=S.fitted.h,x=Math.max(0,Math.min(w-1,Math.round(xf*(w-1)))),y=Math.max(0,Math.min(h-1,Math.round(yf*(h-1)))),n=S.fitted.labels[y*w+x];return(n>=1&&n<=5)?n:0}
async function generate(){busy(true,'GeoJSON-Konturen werden automatisch erzeugt …');await new Promise(r=>setTimeout(r,20));try{const[c,r]=[200,260],features=[],p=palette();for(let n=1;n<=5;n++){const vals=[];for(let y=0;y<r;y++)for(let x=0;x<c;x++)vals.push(sampleFit((x+.5)/c,(y+.5)/r)===n?1:0);const co=d3.contours().size([c,r]).smooth(true).thresholds([.5])(vals)[0];if(!co?.coordinates?.length)continue;let f=turf.feature({type:'MultiPolygon',coordinates:co.coordinates.map(poly=>poly.map(q=>q.map(([x,y])=>point(x,y,c,r))))},{wbi_stufe:n,wbi_text:LV[n].t,farbe:p.colors[n],prognosetag:S.day,datum:new Date(Date.now()+S.day*86400000).toISOString().slice(0,10),quelle:'DWD-PNG, Grenzlinien bereinigt und auf DWD-WFS-Geometrie angepasst'});try{f=turf.intersect(f,S.mask);if(!f)continue;f=turf.simplify(f,{tolerance:.0025,highQuality:true});f.properties={wbi_stufe:n,wbi_text:LV[n].t,farbe:p.colors[n],prognosetag:S.day,datum:new Date(Date.now()+S.day*86400000).toISOString().slice(0,10),quelle:'DWD-PNG, Grenzlinien bereinigt und auf DWD-WFS-Geometrie angepasst'}}catch(e){console.warn(e)}features.push(f)}S.geo={type:'FeatureCollection',metadata:{titel:'Waldbrandgefahrenindex Deutschland',quelle:'Deutscher Wetterdienst',geometrie:'DWD-WFS Deutschland/Bundesländer',koordinatensystem:'WGS 84 / EPSG:4326',farbschema:p.name,hinweis:'Bundeslandlinien wurden vor der WBI-Flächenberechnung entfernt.'},features};renderVector();$('download').disabled=!features.length;note('GeoJSON-Flächen wurden automatisch im Standard-Detailgrad erzeugt.','ok')}catch(e){note(e.message,'err')}finally{busy(false)}}
$('day').onchange=()=>loadDay();$('palette').onchange=applyPalette;$('download').onclick=()=>{if(!S.geo)return;const u=URL.createObjectURL(new Blob([JSON.stringify(S.geo,null,2)],{type:'application/geo+json'})),a=document.createElement('a');a.href=u;a.download=`waldbrandgefahrenindex_${S.palette}_${new Date(Date.now()+S.day*86400000).toISOString().slice(0,10)}.geojson`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};init();
