/*
WBI GEOlayers Einfärber – Aktuell-Farben
Für Adobe After Effects / GEOlayers 3
*/
(function(thisObj){
"use strict";
var NAME="Aktuell-Farben";
var P=[{l:5,n:"Sehr hohe Gefahr",f:"WBI 5 \u2013 Sehr hohe Gefahr",h:"#71207f",c:[113/255,32/255,127/255]},{l:1,n:"Sehr geringe Gefahr",f:"WBI 1 \u2013 Sehr geringe Gefahr",h:"#c1bdb2",c:[193/255,189/255,178/255]},{l:4,n:"Hohe Gefahr",f:"WBI 4 \u2013 Hohe Gefahr",h:"#c61e1e",c:[198/255,30/255,30/255]},{l:3,n:"Mittlere Gefahr",f:"WBI 3 \u2013 Mittlere Gefahr",h:"#ff8b00",c:[255/255,139/255,0/255]},{l:2,n:"Geringe Gefahr",f:"WBI 2 \u2013 Geringe Gefahr",h:"#fec804",c:[254/255,200/255,4/255]}];
function norm(v){return String(v===undefined||v===null?"":v).toLowerCase().replace(/\u00e4/g,"ae").replace(/\u00f6/g,"oe").replace(/\u00fc/g,"ue").replace(/\u00df/g,"ss").replace(/[\u2013\u2014]/g,"-").replace(/[^a-z0-9]+/g," ").replace(/^\s+|\s+$/g,"");}
function byLevel(l){for(var i=0;i<P.length;i++)if(P[i].l===l)return P[i];return null;}
function hasLevel(s,l){s=norm(s);return new RegExp("(^| )(wbi ?|stufe |index |gefahr )"+l+"($| )").test(s);}
function detect(v){var s=norm(v);if(!s)return null;if(s.indexOf("sehr hohe gefahr")>=0||hasLevel(s,5))return byLevel(5);if(s.indexOf("sehr geringe gefahr")>=0||hasLevel(s,1))return byLevel(1);if(s.indexOf("mittlere gefahr")>=0||hasLevel(s,3))return byLevel(3);if(s.indexOf("hohe gefahr")>=0||hasLevel(s,4))return byLevel(4);if(s.indexOf("geringe gefahr")>=0||hasLevel(s,2))return byLevel(2);return null;}
function setColor(p,c){try{if(p.numKeys>0){for(var k=1;k<=p.numKeys;k++)p.setValueAtKey(k,c);}else p.setValue(c);return true;}catch(e){return false;}}
function colorTree(g,e,strokes){var r={f:0,s:0};if(!g||!g.numProperties)return r;for(var i=1;i<=g.numProperties;i++){var p;try{p=g.property(i);}catch(x){continue;}if(!p)continue;try{if(p.matchName==="ADBE Vector Fill Color"){if(setColor(p,e.c))r.f++;continue;}if(strokes&&p.matchName==="ADBE Vector Stroke Color"){if(setColor(p,e.c))r.s++;continue;}}catch(x){}try{if(p.numProperties>0){var n=colorTree(p,e,strokes);r.f+=n.f;r.s+=n.s;}}catch(x){}}return r;}
function addFill(g,e){try{if(!g||!g.canAddProperty("ADBE Vector Graphic - Fill"))return false;var f=g.addProperty("ADBE Vector Graphic - Fill"),c=f.property("ADBE Vector Fill Color");if(c)c.setValue(e.c);return true;}catch(x){return false;}}
function group(g,opt){var e=detect(g.name);if(!e)return null;var r=colorTree(g,e,opt.strokes);if(!r.f)try{if(addFill(g.property("ADBE Vectors Group"),e))r.f++;}catch(x){}if(opt.rename)try{g.name=e.f;}catch(x){}return{e:e,f:r.f,s:r.s};}
function layerText(l){var a=[];try{a.push(l.name);}catch(x){}try{if(l.comment)a.push(l.comment);}catch(x){}try{if(l.source&&l.source.name)a.push(l.source.name);}catch(x){}return a.join(" | ");}
function process(l,opt){var root;try{root=l.property("ADBE Root Vectors Group");}catch(x){return null;}if(!root)return null;var m=0,f=0,s=0,first=null;for(var i=1;i<=root.numProperties;i++){var g;try{g=root.property(i);}catch(x){continue;}if(!g||g.matchName!=="ADBE Vector Group")continue;var q=group(g,opt);if(q){m++;f+=q.f;s+=q.s;if(!first)first=q.e;}}if(m){if(opt.rename&&m===1&&first)try{l.name=first.f;}catch(x){}return{m:m,f:f,s:s};}var e=detect(layerText(l));if(!e)return null;var r=colorTree(root,e,opt.strokes);if(!r.f&&addFill(root,e))r.f++;if(opt.rename)try{l.name=e.f;}catch(x){}return{m:1,f:r.f,s:r.s};}
function run(opt,status){var comp=app.project.activeItem;if(!(comp instanceof CompItem)){alert("Bitte zuerst die GEOlayers-Komposition öffnen.");return;}var layers=[],i;if(opt.selected&&comp.selectedLayers&&comp.selectedLayers.length){for(i=0;i<comp.selectedLayers.length;i++)layers.push(comp.selectedLayers[i]);}else for(i=1;i<=comp.numLayers;i++)layers.push(comp.layer(i));var lm=0,fm=0,fc=0,sc=0;app.beginUndoGroup("WBI einfärben – "+NAME);try{for(i=0;i<layers.length;i++){if(!(layers[i] instanceof ShapeLayer))continue;var r=process(layers[i],opt);if(!r)continue;lm++;fm+=r.m;fc+=r.f;sc+=r.s;}}catch(e){alert("Fehler beim Einfärben:\n\n"+e.toString()+(e.line?"\nZeile: "+e.line:""));}finally{app.endUndoGroup();}status.text=lm+" Shape-Ebene(n), "+fm+" WBI-Fläche(n), "+fc+" Füllung(en) mit "+NAME+" eingefärbt"+(opt.strokes?", "+sc+" Kontur(en)":"")+".";if(!fm)alert("Keine benannten WBI-Flächen gefunden.\n\nErwartet werden Namen wie „Sehr hohe Gefahr“, „WBI 4 – Hohe Gefahr“ oder „Mittlere Gefahr“.");}
function ui(){var w=(thisObj instanceof Panel)?thisObj:new Window("palette","WBI GEOlayers Einfärber – "+NAME,undefined,{resizeable:true});w.orientation="column";w.alignChildren=["fill","top"];w.spacing=8;w.margins=12;w.add("statictext",undefined,"Färbt GEOlayers-Shape-Flächen automatisch mit „"+NAME+"“ ein.",{multiline:true});var o=w.add("panel",undefined,"Optionen");o.orientation="column";o.alignChildren=["left","top"];o.margins=10;var selected=o.add("checkbox",undefined,"Nur ausgewählte Ebenen");selected.value=true;var strokes=o.add("checkbox",undefined,"Konturen ebenfalls einfärben");var rename=o.add("checkbox",undefined,"Erkannte Ebenen und Gruppen umbenennen");rename.value=true;var pp=w.add("panel",undefined,"Farben · "+NAME);pp.orientation="column";pp.alignChildren=["left","top"];pp.margins=10;var order=[5,4,3,2,1];for(var i=0;i<order.length;i++){var e=byLevel(order[i]);pp.add("statictext",undefined,e.f+": "+e.h);}var b=w.add("button",undefined,"WBI-Flächen einfärben"),status=w.add("statictext",undefined,"Bereit · "+NAME+".",{multiline:true});b.onClick=function(){run({selected:selected.value,strokes:strokes.value,rename:rename.value},status);};w.onResizing=w.onResize=function(){this.layout.resize();};if(w instanceof Window){w.center();w.show();}else w.layout.layout(true);}
ui();
})(this);
